app:
  image: golang:1.8
  tty: true
  links:
    - db
  volumes:
    - "./app:/go/src/app"
#  command: go run /go/src/app/main.go
db:
  image: mysql:5.7
  volumes:
    - ./db/mysql_data:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=app