app:
  image: golang:1.8
  tty: true
  links:
    - db
  volumes:
    - "./app:/go/src/github.com/techlink/cli"
db:
  build: .
  dockerfile: Dockerfile-MySQL
  volumes:
    - ./db/mysql_data:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=app
  command: mysqld --sql_mode="" --character-set-server=utf8 --collation-server=utf8_general_ci